const COMMAND_TYPE = {
    PLACE: "PLACE",
    MOVE: "MOVE",
    MOVE_AIR_UNIT: "MOVE AIR UNIT",
    MOVE_FLEET_UNIT: "MOVE FLEET UNIT",
    MOVE_STRIKE_GROUP: "MOVE STRIKE GROUP",
    DIE_ROLLS: "DIE-ROLLS",
    SELECT_TARGET: "SELECT TARGET",
    TARGET_STATUS_CHANGE: "TARGET STATUS CHANGE",
    INITIATIVE_STATUS_CHANGE: "INITIATIVE STATUS CHANGE",
    SELECT_CAP_UNITS: "SELECT CAP UNITS",
    ALLOCATE_DAMAGE: "ALLOCATE DAMAGE",
    CARRIER_DAMAGE_BOW: "CARRIER DAMAGE BOW",
    CARRIER_DAMAGE_STERN: "CARRIER DAMAGE STERN",
    CARRIER_SUNK: "CARRIER SUNK"
}

export default COMMAND_TYPE;