const COMMAND_TYPE = {
    PLACE: "PLACE",
    MOVE: "MOVE",
    MOVE_AIR_UNIT: "MOVE AIR UNIT",
    MOVE_FLEET_UNIT: "MOVE FLEET UNIT",
    MOVE_STRIKE_GROUP: "MOVE STRIKE GROUP",
    DROP: "DROP",
    DIE_ROLLS: "DIE-ROLLS",
    SELECT_TARGET: "SELECT TARGET",
    TARGET_STATUS_CHANGE: "TARGET STATUS CHANGE",
    INITIATIVE_STATUS_CHANGE: "INITIATIVE STATUS CHANGE"
}

export default COMMAND_TYPE;